[package]
name = "autograd_study"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autograd = { version = "1.1.0", features = ["mkl"] }
